### PR TITLE
24.02 User Guide Update

### PR DESCRIPTION
**Pull request by offset-torque**
Changelog provided here: https://github.com/koreader/koreader/issues/11147#issuecomment-1962981373

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader.github.io/43)

### CODE REVIEW

**Comment by offset-torque** [comment]
Is there anything else I should do @Frenzie ?

**Comment by Frenzie** [comment]
Strange, the preview doesn't seem to be working. But no, this is all excellent.

**Comment by Frenzie** [comment]
@offset-torque #45 might unfortunately make life a little bit more annoying for you, but it'll warn us in the PR if a change is at risk of breaking Weblate. Though as long as you allow edits by maintainers on a PR you can also ask me to take care of it before merging. ;-)

**Comment by offset-torque** [comment]
Thanks for fixing it Frenzie. VS Code didn't show any problems and page rendered properly in the browser checks so I didn't notice it. No problem for me, I don't want to break Weblate :)

**Pull request merged**
