### PR TITLE
Fix last update date

### PR DESCRIPTION
**Pull request by offset-torque**
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader.github.io/23)

### CODE REVIEW

**Comment by offset-torque** [comment]
I think we can go online with the guide Frenzie. Thanks.

**Comment by Frenzie** [comment]
Btw, you should have full access to manage this repo now. For something tiny like this it can occasionally be okay to skip a PR but normally we use PRs so that everyone knows what's going on.

**Comment by offset-torque** [comment]
I understand. I suppose now I can approve my own PR's too. Should I always wait for you to approve or for small updates can I approve to not bother you.

**Comment by Frenzie** [comment]
For something inconsequential like this you can just click "squash and merge" or "rebase and merge" immediately. The PR merely serves as a notification then. For something bigger it's better to wait a day or two before merging so people have a chance to comment, or of course you can always ping if you specifically want someone to take a look.

**Pull request merged**
