### PR TITLE
Link to ZIP wiki page

### PR DESCRIPTION
**Pull request by clach04**
Related to:

  * https://github.com/koreader/koreader/issues/9986 - new ZIP wiki page
  * https://github.com/koreader/koreader/pull/10004 - update readme.md

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader.github.io/18)

### CODE REVIEW

**Comment by Frenzie** [comment]
I understand wanting to mention more features, but I'd prefer to keep the homepage free from distractions. Perhaps that should mean not mentioning zip files at all (nor mobi for that matter).

**Comment by NiLuJe** [comment]
Nor DOC nor RTF if we're being honest ;).

**Comment by Frenzie** [comment]
I don't know about DOC or RTF but I have found the DOC*X* support useful because it shows you the text and images in a way that works well on your ereader or your phone. The lack of support for positioning etc. feels more like a feature for that use case.

I feel there's a bit of a distinction there with mobi with regard to expectations.

**Comment by Frenzie** [comment]
Closing as explained. Thanks for the PR though! ^_^

**Pull request closed without merging**
